version: '3.8'

services:
  tasks-processor1:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - CONTAINER_PORT=${PORT}
    env_file: .env  
    ports:
      - "${PORT}:${PORT}"
    restart: unless-stopped
  tasks-processor2:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - CONTAINER_PORT=${PORT2}
    env_file: .env  
    ports:
      - "${PORT2}:${PORT2}"
    restart: unless-stopped
  main-db:
    image: postgres
    restart: always
    ports:
      - 5434:5432
    env_file: .env
    environment:
      - "POSTGRES_USER=${DB_USERNAME}"
      - "POSTGRES_PASSWORD=${DB_PASSWORD}"
      - "POSTGRES_DB=${DATABASE}"
    volumes:
      - tasks-db:/var/lib/postgresql/data
volumes:
  tasks-db:

